In [ ]:
import pandas as pd

In [ ]:
# Load the 'BIDWESH Dataset.csv' file
df_bidwesh = pd.read_csv('BIDWESH Dataset.csv')

# Display the first 5 rows of the BIDWESH Dataset
print("BIDWESH Dataset:")
display(df_bidwesh.head())

BIDWESH Dataset:

,Chittagong,Noakhali,Barishal,target,type,hate speech
0,গরুর বাইচ্চা কুত্তার বাইচ্চা।,গরুর বাইচ্ছা কুত্তার বাইচ্ছা,গরুর বাচ্চা কুত্তার বাচ্চা।,ind,slander,1
1,"ক্রিকেটরাগো অন্যায় দাবিত অয়, তবুও দোষ বোর্ডর! ...",অন্যায় দাবি কইচ্ছে ক্রিকেটারেরা হেও দোষ বলে ব...,অন্যায় দাবি হরছে ক্রিকেটাররা হেরপরেও দোষ নাহি ...,ind,religion,1
2,আইসিসি লগে খবর খনে দিল? শুয়েরর ফুয়া চাই।,আইসিসিরে এই খবর দিসে কনে? শুয়োরের বাইচ্ছা পাপ...,আইসিসিকে এই কতা কইছে কেডা? শুওরের বাচ্চা পাপন।,male,slander,1
3,"আগারওয়াল পুরা হারামজাদা, তোর কিসু ন কইব?",আগারওয়াল পুরা বাস্টার্ড এর কিসু ঐতোনো?,আগারওয়াল খাটি হারামজাদা অর কিচ্ছু অইবে না?,ind,slander,1
4,তু হালা বেয়াক্কেল।,আবাইল্লা তুই।,আবাল তই।,ind,slander,1

In [ ]:
# Load the 'Regional Translated Texts.csv' file
df_regional = pd.read_csv('Regional Translated Texts.csv')

# Display the first 5 rows of the Regional Translated Texts Dataset
print("\nRegional Translated Texts Dataset:")
display(df_regional.head())

Regional Translated Texts Dataset:

,Standard Bangla,Chittagong,Noakhali,Barishal
0,। গরুর বাচ্চা কুকুরের বাচ্চা,গরুর বাইচ্চা কুত্তার বাইচ্চা।,গরুর বাইচ্ছা কুত্তার বাইচ্ছা,গরুর বাচ্চা কুত্তার বাচ্চা।
1,অন্যায় দাবি করছে ক্রিকেটাররা অথচ দোষ নাকি বোর্...,"ক্রিকেটরাগো অন্যায় দাবিত অয়, তবুও দোষ বোর্ডর! ...",অন্যায় দাবি কইচ্ছে ক্রিকেটারেরা হেও দোষ বলে ব...,অন্যায় দাবি হরছে ক্রিকেটাররা হেরপরেও দোষ নাহি ...
2,আইসিসিকে এই তথ্য দিলো কে?শুওরের বাচ্চা পাপন,আইসিসি লগে খবর খনে দিল? শুয়েরর ফুয়া চাই।,আইসিসিরে এই খবর দিসে কনে? শুয়োরের বাইচ্ছা পাপ...,আইসিসিকে এই কতা কইছে কেডা? শুওরের বাচ্চা পাপন।
3,আগারওয়াল পিউর বাস্টার্ড এর কিছু হবে না???,"আগারওয়াল পুরা হারামজাদা, তোর কিসু ন কইব?",আগারওয়াল পুরা বাস্টার্ড এর কিসু ঐতোনো?,আগারওয়াল খাটি হারামজাদা অর কিচ্ছু অইবে না?
4,আবাল তুই,তু হালা বেয়াক্কেল।,আবাইল্লা তুই।,আবাল তই।

In [ ]:
display(df_bidwesh['Chittagong'])

0                           গরুর বাইচ্চা কুত্তার বাইচ্চা।
1       ক্রিকেটরাগো অন্যায় দাবিত অয়, তবুও দোষ বোর্ডর! ...
2              আইসিসি লগে  খবর খনে  দিল? শুয়েরর ফুয়া চাই।
3               আগারওয়াল পুরা হারামজাদা, তোর কিসু  ন কইব?
4                                      তু হালা বেয়াক্কেল।
                              ...
3056                                      আঁঁই যাইতু সাই।
3057            আঁই রানু দিদিরে বাগত ফাইলে হাডি ফালাইয়ুম।
3058    আঁই শাকিব খানোল্লগে একমত ইবে যা হইয়্যি উসিত হত...
3059                                    আঁই শেয়ার গইজ্জি।
3060     আঁই ইন্দু অইয়েনে হইদ্দি মোদি সাওয়ালার ফাঁসি সাই।
Name: Chittagong, Length: 3061, dtype: object

In [ ]:
# Create a DataFrame with only the 'Chittagong' column
df_chittagong = df_bidwesh[['Chittagong']]

# Save this DataFrame to 'THT_dataset.csv'
df_chittagong.to_csv('THT_dataset.csv', index=False)
print(" 'Chittagong' column successfully copied to 'THT_dataset.csv'")

 'Chittagong' column successfully copied to 'THT_dataset.csv'

In [ ]:
# Load the newly created 'THT_dataset.csv' to verify
df_tht = pd.read_csv('THT_dataset.csv')

# Display the first few rows of the new DataFrame
print("\nContent of THT_dataset.csv:")
display(df_tht.head())

Content of THT_dataset.csv:

                                          Chittagong
0                      গরুর বাইচ্চা কুত্তার বাইচ্চা।
1  ক্রিকেটরাগো অন্যায় দাবিত অয়, তবুও দোষ বোর্ডর! ...
2         আইসিসি লগে  খবর খনে  দিল? শুয়েরর ফুয়া চাই।
3          আগারওয়াল পুরা হারামজাদা, তোর কিসু  ন কইব?
4                                 তু হালা বেয়াক্কেল।

In [ ]:
import pandas as pd

# Load the existing THT_dataset.csv (which contains 'Chittagong')
df_tht_existing = pd.read_csv('THT_dataset.csv')

# Select the additional columns from df_bidwesh
df_noakhali_barishal = df_bidwesh[['Noakhali', 'Barishal']]

# Select 'Standard Bangla' column from df_regional
df_standard_bangla = df_regional[['Standard Bangla']]

# Concatenate all selected columns to form the new THT_dataset content
df_tht_combined = pd.concat([df_tht_existing, df_noakhali_barishal, df_standard_bangla], axis=1)

# Save the combined DataFrame to THT_dataset.csv, overwriting the previous one
df_tht_combined.to_csv('THT_dataset.csv', index=False)
print("Columns 'Noakhali', 'Barishal', and 'Standard Bangla' successfully added to 'THT_dataset.csv'.")

# Load the newly updated 'THT_dataset.csv' to verify and display
df_tht_updated = pd.read_csv('THT_dataset.csv')

# Display the first few rows of the updated DataFrame
print("\nContent of updated THT_dataset.csv:")
display(df_tht_updated.head())

# Display the total number of entries (rows)
total_entries = len(df_tht_updated)
print(f"\nTotal data count in THT_dataset.csv: {total_entries} entries")

Columns 'Noakhali', 'Barishal', and 'Standard Bangla' successfully added to 'THT_dataset.csv'.

Content of updated THT_dataset.csv:

,Chittagong,Noakhali,Barishal,Standard Bangla
0,গরুর বাইচ্চা কুত্তার বাইচ্চা।,গরুর বাইচ্ছা কুত্তার বাইচ্ছা,গরুর বাচ্চা কুত্তার বাচ্চা।,। গরুর বাচ্চা কুকুরের বাচ্চা
1,"ক্রিকেটরাগো অন্যায় দাবিত অয়, তবুও দোষ বোর্ডর! ...",অন্যায় দাবি কইচ্ছে ক্রিকেটারেরা হেও দোষ বলে ব...,অন্যায় দাবি হরছে ক্রিকেটাররা হেরপরেও দোষ নাহি ...,অন্যায় দাবি করছে ক্রিকেটাররা অথচ দোষ নাকি বোর্...
2,আইসিসি লগে খবর খনে দিল? শুয়েরর ফুয়া চাই।,আইসিসিরে এই খবর দিসে কনে? শুয়োরের বাইচ্ছা পাপ...,আইসিসিকে এই কতা কইছে কেডা? শুওরের বাচ্চা পাপন।,আইসিসিকে এই তথ্য দিলো কে?শুওরের বাচ্চা পাপন
3,"আগারওয়াল পুরা হারামজাদা, তোর কিসু ন কইব?",আগারওয়াল পুরা বাস্টার্ড এর কিসু ঐতোনো?,আগারওয়াল খাটি হারামজাদা অর কিচ্ছু অইবে না?,আগারওয়াল পিউর বাস্টার্ড এর কিছু হবে না???
4,তু হালা বেয়াক্কেল।,আবাইল্লা তুই।,আবাল তই।,আবাল তুই

Total data count in THT_dataset.csv: 3061 entries

In [ ]:
import pandas as pd

df_translated = pd.read_csv('THT_dataset_translated.csv')
print('Content of THT_dataset_translated.csv:')
display(df_translated)

Content of THT_dataset_translated.csv:

,Chittagong,Noakhali,Barishal,Standard Bangla,Standard Bangla English
0,গরুর বাইচ্চা কুত্তার বাইচ্চা।,গরুর বাইচ্ছা কুত্তার বাইচ্ছা,গরুর বাচ্চা কুত্তার বাচ্চা।,। গরুর বাচ্চা কুকুরের বাচ্চা,। son of a cow son of a dog
1,"ক্রিকেটরাগো অন্যায় দাবিত অয়, তবুও দোষ বোর্ডর! ...",অন্যায় দাবি কইচ্ছে ক্রিকেটারেরা হেও দোষ বলে ব...,অন্যায় দাবি হরছে ক্রিকেটাররা হেরপরেও দোষ নাহি ...,অন্যায় দাবি করছে ক্রিকেটাররা অথচ দোষ নাকি বোর্...,unfair demand is making the cricketers but bla...
2,আইসিসি লগে খবর খনে দিল? শুয়েরর ফুয়া চাই।,আইসিসিরে এই খবর দিসে কনে? শুয়োরের বাইচ্ছা পাপ...,আইসিসিকে এই কতা কইছে কেডা? শুওরের বাচ্চা পাপন।,আইসিসিকে এই তথ্য দিলো কে?শুওরের বাচ্চা পাপন,to ICC this information gave who?son of a pig ...
3,"আগারওয়াল পুরা হারামজাদা, তোর কিসু ন কইব?",আগারওয়াল পুরা বাস্টার্ড এর কিসু ঐতোনো?,আগারওয়াল খাটি হারামজাদা অর কিচ্ছু অইবে না?,আগারওয়াল পিউর বাস্টার্ড এর কিছু হবে না???,আগারওয়াল pure bastard of anything will happen ...
4,তু হালা বেয়াক্কেল।,আবাইল্লা তুই।,আবাল তই।,আবাল তুই,idiot you
...,...,...,...,...,...
3056,আঁঁই যাইতু সাই।,আই যাইতে চাই।,মুই যাইতে চাই।,আমি যাইতে চাই,আমি যাইতে চাই
3057,আঁই রানু দিদিরে বাগত ফাইলে হাডি ফালাইয়ুম।,আই রানু দিদি রে কাছে হাইলে কাটি ফেলমু।,মুই রানু দিদিরে ধারে পাইলে কাইট্টা ফ্যালতাম।,আমি রানু দিদি কে কাছে পেল কেটে ফেলবো,আমি রানু দিদি who কাছে পেল whoটে ফেলবো
3058,আঁই শাকিব খানোল্লগে একমত ইবে যা হইয়্যি উসিত হত...,আঁই শাকিব খানের লগে একমত হেতে যা কইছে উচিত কতা...,মুই শাকিব খানের লগে একমত ও যা কইছে উচিৎ কতা কই...,আমি শাকিব খানের সাথে একমত ও যা বলেছে উচিত কথা ...,আমি শাকিব খানের সাথে একমত ও যা বলেছে উচিত কথা ...
3059,আঁই শেয়ার গইজ্জি।,আঁই সেয়ার ক‌ইচ্ছি।,মুই সেয়ার হরছি।,আমি সেয়ার করেছি,আমি সেয়ার করেছি
3060,আঁই ইন্দু অইয়েনে হইদ্দি মোদি সাওয়ালার ফাঁসি সাই।,আমি হিন্দু হয়েবলচি মদিচাআলা ফাসিচাই।,মুই হিন্দু অইয়া কইতাছি মোদি চা আলা ফাসি চাই।,আমি হিন্দু হয়েবলচি মদিচাআলা ফাসিচাই,আমি হিন্দু হয়েবলচি মদিচাআলা ফাসিচাই